name: GKE Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - id: "auth"
        uses: "google-github-actions/auth@v3"
        with:
          workload_identity_provider: "projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider"

      - name: "deploy with gke-deploy cli"
        uses: "google-github-actions/deploy-gke@v0"
        with:
          image: "my-image"
          app_name: "sicheong"
          region: "asia-northeast3"
          cluster_name: "sicheong-cluster"
          project_id: "sicheong-1"
          # namespace: "my-namespace"
          expose: "8000"
          # k8s_manifests: "configs"

      - name: "get-deployments"
        shell: bash
        run: |
          kubectl get pods -n my-namespace
          kubectl get deployment -n my-namespace
